apiVersion: v1
kind: Namespace
metadata:
  name:  nspod
  labels:
    env : dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: nsservices
  labels:
    env : dev

---
apiVersion: v1
kind: Deployment
metadata:
  name:  apppod
  labels:
    env: dev
spec:
  containers:
  - name:  app-nginx
    image:  nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - name:  nginxport
      port:  80
      protocol: TCP
